# Generated by Django 6.1.1 on 2026-09-10 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
