# Generated by Django 6.1.1 on 2026-09-05 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Pending Review'), ('approved', 'Approved'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('executive_summary', models.TextField(blank=True)),
                ('project_overview', models.TextField(blank=True)),
                ('scope_summary', models.TextField(blank=True)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=dict)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('client_requirements', models.JSONField(blank=True, default=list)),
                ('third_party_notes', models.JSONField(blank=True, default=list)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('internal_notes', models.TextField(blank=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='crm.lead')),
                ('pricing_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='proposals.pricingregion')),
                ('project_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.projectrequest')),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.quoterequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('assistant', 'AB AI'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='proposals.proposalconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('client_request', models.TextField(blank=True)),
                ('scope_snapshot', models.JSONField(blank=True, default=dict)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('base', 'Base'), ('feature', 'Feature'), ('page', 'Page'), ('integration', 'Integration'), ('api', 'API'), ('authentication', 'Authentication'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('security', 'Security'), ('mobile', 'Mobile'), ('custom', 'Custom')], max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('included_quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='proposals.pricingregion')),
            ],
            options={
                'ordering': ['rule_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('region', 'code'), name='unique_pricing_rule_per_region')],
            },
        ),
    ]
