# Generated by Django 6.1.1 on 2026-09-05 12:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='pricing_region',
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='region',
            field=models.CharField(default='NG', help_text='Country/region code, e.g. NG, US, CA.', max_length=100),
        ),
        migrations.RemoveField(
            model_name='proposalconversation',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalmessage',
            name='conversation',
        ),
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='pricingrule',
            name='unique_pricing_rule_per_region',
        ),
        migrations.RenameField(
            model_name='pricingrule',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricingrule',
            old_name='included_quantity',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='generated_by_ai',
            new_name='client_editable',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='executive_summary',
            new_name='client_summary',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='client_requirements',
            new_name='exclusions',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='terms',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='third_party_notes',
            new_name='integrations',
        ),
        migrations.RenameField(
            model_name='proposalrevision',
            old_name='scope_snapshot',
            new_name='ai_analysis',
        ),
        migrations.RenameField(
            model_name='proposalrevision',
            old_name='client_request',
            new_name='client_summary',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='project_overview',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_number',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='scope_summary',
        ),
        migrations.RemoveField(
            model_name='proposalrevision',
            name='reason',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='category',
            field=models.CharField(choices=[('website', 'Website'), ('mobile', 'Mobile'), ('backend', 'Backend/API'), ('authentication', 'Authentication'), ('integration', 'Integration'), ('devops', 'DevOps'), ('feature', 'Feature'), ('other', 'Other')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='unit',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('per_unit', 'Per Unit'), ('per_page', 'Per Page')], default='fixed', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='source',
            field=models.CharField(choices=[('project_request', 'Project Request'), ('quote_request', 'Quote Request'), ('manual', 'Manual')], default='project_request', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='technical_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='assumptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='deliverables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='integrations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='source',
            field=models.CharField(choices=[('ai', 'AI'), ('client', 'Client'), ('staff', 'Staff')], default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='technical_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='timeline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Raw normalized Proposal AI analysis.'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Internal pricing calculation. Never expose directly to client.'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Review'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='proposalrevision',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposalrevision',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddConstraint(
            model_name='proposalrevision',
            constraint=models.UniqueConstraint(fields=('proposal', 'version'), name='unique_proposal_revision_version'),
        ),
        migrations.DeleteModel(
            name='PricingRegion',
        ),
        migrations.DeleteModel(
            name='ProposalConversation',
        ),
        migrations.DeleteModel(
            name='ProposalMessage',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='unit_price',
        ),
    ]
