# Generated by Django 6.1.1 on 2026-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposal_pricing_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accepted_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='authentication',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='backend',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='devops',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='Internal and client-facing project milestones.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='mobile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='authentication',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='backend',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='change_summary',
            field=models.TextField(blank=True, help_text='What changed from the previous version.'),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='devops',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalrevision',
            name='mobile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='category',
            field=models.CharField(choices=[('website', 'Website'), ('mobile', 'Mobile'), ('backend', 'Backend/API'), ('authentication', 'Authentication'), ('integration', 'Integration'), ('devops', 'DevOps'), ('feature', 'Feature'), ('training', 'Training'), ('procurement', 'Procurement'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='region',
            field=models.CharField(default='NG', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
