# Generated by Django 6.1.1 on 2026-09-05 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_accepted_version_proposal_authentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
