# Generated by Django 6.1.1 on 2026-09-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='business_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='confirmed_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='executive_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='optional_future_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recommended_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recurring_costs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='security',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProposalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('recommended', 'Recommended'), ('optional', 'Optional'), ('future', 'Future'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='confirmed', max_length=30)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('client', 'Client'), ('admin', 'Admin')], default='ai', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_features', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requirement_type', models.CharField(choices=[('confirmed', 'Confirmed'), ('recommended', 'Recommended'), ('optional', 'Optional'), ('future', 'Future')], max_length=30)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('client', 'Client'), ('admin', 'Admin')], default='ai', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('user_type', models.CharField(blank=True, max_length=100)),
                ('components', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('status', models.CharField(default='confirmed', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='proposals.proposal')),
            ],
        ),
    ]
