# Generated by Django 6.1.1 on 2026-09-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('proposals', '0005_proposal_business_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
