# Generated by Django 6.1.1 on 2026-09-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('proposals', '0006_proposal_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='organizations.organization'),
        ),
    ]
