# Generated by Django 6.1.1 on 2026-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_alter_proposal_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalfeature',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='proposalfeature',
            name='scope_status',
            field=models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='required', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalfeature',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='approved', max_length=20),
        ),
    ]
