# Generated by Django 6.1.1 on 2026-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_proposalfeature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalscreen',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.RenameField(
            model_name='proposalscreen',
            old_name='components',
            new_name='data_involved',
        ),
        migrations.RenameField(
            model_name='proposalscreen',
            old_name='user_type',
            new_name='screen_type',
        ),
        migrations.AddField(
            model_name='proposalscreen',
            name='complexity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='proposalscreen',
            name='dependencies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='proposalscreen',
            name='key_functionality',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='proposalscreen',
            name='major_components',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='proposalscreen',
            name='user_roles',
            field=models.JSONField(default=list),
        ),
    ]
