# Generated by Django 6.1.1 on 2026-09-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_proposalscreen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfeature',
            name='is_included',
            field=models.BooleanField(default=False),
        ),
    ]
