# Generated by Django 6.1.1 on 2026-09-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_proposalfeature_is_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('action', models.CharField(choices=[('comment', 'Comment'), ('accept', 'Acceptance'), ('decline', 'Decline')], default='comment', max_length=20)),
                ('author_type', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
