# Generated by Django 6.1.1 on 2026-09-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_proposalcomment_author_proposalcomment_milestone_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Review'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
