# Generated by Django 6.1.1 on 2026-09-19 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_alter_proposal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('payment_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='locked', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('not_required', 'Not Required')], default='unpaid', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_records', to='proposals.proposal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('partial', 'Partial Payment'), ('balance', 'Balance Payment'), ('full', 'Full Payment'), ('other', 'Other')], default='partial', max_length=30)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30)),
                ('transaction_reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('refund_status', models.CharField(choices=[('none', 'No Refund'), ('partial', 'Partially Refunded'), ('full', 'Fully Refunded')], default='none', max_length=20)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_proposal_payments', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='proposals.proposalmilestone')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposalmilestone',
            index=models.Index(fields=['proposal', 'order'], name='proposals_p_proposa_ad5982_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalmilestone',
            index=models.Index(fields=['proposal', 'payment_status'], name='proposals_p_proposa_2f9c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalpayment',
            index=models.Index(fields=['proposal', 'status'], name='proposals_p_proposa_c5fcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalpayment',
            index=models.Index(fields=['transaction_reference'], name='proposals_p_transac_0babfe_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalpayment',
            index=models.Index(fields=['provider_reference'], name='proposals_p_provide_cb4cad_idx'),
        ),
    ]
