# Generated by Django 6.1.1 on 2026-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_quoterequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementquotationitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='request_type',
            field=models.CharField(choices=[('procurement', 'Procurement'), ('service', 'Service'), ('product', 'Product'), ('mixed', 'Mixed'), ('other', 'Other')], default='procurement', max_length=30),
        ),
    ]
