# Generated by Django 6.1.1 on 2026-09-15 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_procurementquotationitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementClientRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('client_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_revisions', to='crm.quoterequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementClientRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quoted_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proposed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('removed', models.BooleanField(default=False)),
                ('client_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_revision_items', to='crm.procurementquotationitem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.procurementclientrevision')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
