# Generated by Django 6.1.1 on 2026-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_procurementclientrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='tracking_reference',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
