# Generated by Django 6.1.1 on 2026-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_quoterequest_tracking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='tracking_reference',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
