# Generated by Django 6.1.1 on 2026-09-17 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_procurementclientrevision_and_more'),
        ('procurement', '0002_alter_procurementrequest_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementTrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_reference', models.CharField(blank=True, editable=False, max_length=50)),
                ('status', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('supplier_confirmed', 'Supplier Confirmed'), ('order_placed', 'Order Placed'), ('processing', 'Processing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='crm.quoterequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_tracking_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
