# Generated by Django 6.1.1 on 2026-09-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementtrackingupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementtrackingupdate',
            name='tracking_reference',
        ),
    ]
